{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "painchain.fullname" . }}-postgresql
  labels:
    {{- include "painchain.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgresql
    protocol: TCP
    name: postgresql
  selector:
    {{- include "painchain.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
